# Generated by Django 3.1.5 on 2021-01-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abbs', '0004_papaabb_downloadurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='papaabb',
            name='iconimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
