# Generated by Django 3.1.5 on 2021-01-24 03:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('abbs', '0005_papaabb_iconimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='papaabb',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='papaabb',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
