# Generated by Django 3.1.5 on 2021-01-24 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abbs', '0007_auto_20210124_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='papaabb',
            options={'ordering': ['-created_date']},
        ),
    ]
