# Generated by Django 3.1.5 on 2021-01-24 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abbs', '0008_auto_20210124_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='papaabb',
            options={},
        ),
    ]
