# Generated by Django 3.1.5 on 2021-10-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abbs', '0009_auto_20210124_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='papaabb',
            name='badgeimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='papaabb',
            name='badgeimage2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='papaabb',
            name='badgeimage3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
