# Generated by Django 3.1.5 on 2021-10-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abbs', '0010_auto_20211022_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='papaabb',
            name='coverimage3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='papaabb',
            name='coverimage4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='papaabb',
            name='subtitle',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
    ]
