# Generated by Django 3.1.5 on 2022-10-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abbs', '0013_getweb_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='papaabb',
            name='videourl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
