# Generated by Django 3.2.16 on 2023-05-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abbs', '0016_papaabb_videourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='papaabb',
            name='coverimage5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='papaabb',
            name='coverimage6',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
