# Generated by Django 2.0.13 on 2019-11-06 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='last_updated',
            new_name='last_modified',
        ),
    ]
