# Generated by Django 3.1.5 on 2021-01-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PapaApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summany', models.TextField(help_text='Enter a brief description of the app', max_length=1000)),
                ('coverimage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('coverimage2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('releasenote', models.TextField(help_text='Enter a brief description of the app', max_length=1000)),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
    ]
